Hw5
ArtyomAfanasov/4thSemester pull request #14
Opened 2019-06-07 14:27 UTC by ArtyomAfanasov

Готово:
Скобки.

2019-06-07 20:31 UTC, yurii-litvinov requested changes

2019-06-07 20:31 UTC, yurii-litvinov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/BracketsSequence.fs
> +                    loop (List.rev (List.rev tail).Tail)
Есть известный и очень простой алгоритм, работающий с помощью стека, за линейное время. У Вас, кажется, квадраитчное получилось.

2019-09-11 13:54 UTC, yurii-litvinov requested changes

2019-09-11 13:54 UTC, yurii-litvinov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/BracketsSequence.fs
> +    let innerDict = new Dictionary<char, char>()
Тут мутабельные структуры данных ещё нельзя было. Да тут они и не нужны, есть F#-овский стандартный Map

2019-09-14 22:05 UTC, yurii-litvinov requested changes

2019-09-14 22:05 UTC, yurii-litvinov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/BracketsSequence.fs
> +    let stack = Stack<char>()
System.Collections.Generic.Stack мутабельный, его нельзя

2019-09-15 13:12 UTC, yurii-litvinov approved these changes
Да, вот теперь всё так, зачтена

2019-09-26 09:14 UTC, yurii-litvinov approved these changes
Ну да, всё так, 5.2 зачтена

2019-10-22 12:37 UTC, yurii-litvinov requested changes
В целом всё ок, но какая-то беда с обработкой ошибок, надо поправить

2019-10-22 12:37 UTC, yurii-litvinov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/Phonebook.fs
> +            Console.Clear()
Console.Clear() делается до match и в начале каждого match-а, странно

2019-10-22 12:37 UTC, yurii-litvinov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/PhonebookLogic.fs
> +        | _ -> phoneAlphabetError
Бросаем исключение и тут же его ловим, что? Причём, ловим не его, а все исключения вообще. Это совсем против идеологии обработки исключений.

2019-10-22 12:37 UTC, yurii-litvinov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/Phonebook.fs
> +                printfn "%s" phoneAlphabetError
То есть если я абонент с именем "Для записи телефона доступны только символы из алфавита: { 0..9, +, -, (, ) }." (ну, мои родители не очень старались, придумывая имя), восвользоваться Вашим сервисом мне не удастся? Нет, так не пойдёт, особенно в функциональных языках, где есть option-ы и choice-ы и прочие discriminated union-ы.

2019-10-22 12:50 UTC, ArtyomAfanasov commented on IntroductionFSharp/Hw5.Generics/Hw5.Generics/Phonebook.fs
> +                printfn "%s" phoneAlphabetError
Это для телефона. Имя может быть любым

2019-11-02 13:32 UTC, merged