Workflow
ArtyomAfanasov/4thSemester pull request #16
Opened 2019-08-27 16:05 UTC by ArtyomAfanasov

2019-08-28 18:41 UTC, yurii-litvinov requested changes
7.1 зачтена, а в 7.2 надо поправить на TryParse, а не ловить исключения, это важно (не касательно F#, а даже касательно программирования вообще)

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/Workflow.Tests/MathCalculationsTests.fs
> +    let rounding calculationAccurancy = new CalculationFlow(calculationAccurancy)
calculationAccuracy, опечатка

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/Workflow.Tests/MathCalculationsTests.fs
> +// ������� �� ���� ���� �� �������.
Лучше писать по-английски (либо выставлять кодировку в .gitattributes)

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/workflow/MathCalculations.fs
> +    // Нужно ли обрабатывать исключение библиотеки?
Обрабатывать исключение библиотеки точно не надо. Не дать Math.Round упасть, вместо этого бросив своё исключение, как тут --- можно, но спорно. С одной стороны, мы можем предоставить пользователю более адекватную диагностику (как тут, внятное сообщение об ошибке), с другой стороны, оно и так бросает ArgumentOutOfRangeException, по которому понятно, что не так, а тут делается лишняя работа. Которая, кстати, ещё смущает тем, что пользователь может подумать, что это Ваша прихоть, а не особенность библиотечной реализации.

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/workflow/MathCalculations.fs
> +        else ()
`else ()` можно не писать --- если ветка then возвращает unit, ветка else опциональна

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/workflow/Program.fs
> +﻿// Learn more about F# at http://fsharp.org
Этот файл можно вообще убрать, если сделать проект не исполняемым файлом, а библиотекой (это в настройках проекта где-то указывается).

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/workflow/StringCalculations.fs
> +    // Подсказывать компилятору, что нужно string? Или в F# это дурной тон?
Принято в функциях и методах, которые может вызывать третьесторонний код, аннотации типов всё-таки писать, в целях документирования хотя бы. Так что тут правильно.

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/workflow/StringCalculations.fs
> +    // Кажется, не подсказывать тут нельзя.
Тем более.

2019-08-28 18:41 UTC, yurii-litvinov commented on workflow/workflow/StringCalculations.fs
> +            | :? System.FormatException -> None
Тут правильнее не ловить исключение, а использовать int.TryParse. Ведь по условию неправильный формат строки допустим, следовательно, это не исключительная ситуация, следовательно, кто-то может в цикле на миллионе строк, половина из кторых плохие, вызывать вычисление, и проиграть в производительности в кучу раз. См. https://mattwarren.org/2016/12/20/Why-Exceptions-should-be-Exceptional/

2019-08-29 09:37 UTC, ArtyomAfanasov commented on workflow/workflow/StringCalculations.fs
> +            | :? System.FormatException -> None
Интересная и полезная статья. Спасибо!

2019-11-02 13:21 UTC, closed without merging