LambdaInterpreter
ArtyomAfanasov/4thSemester pull request #21
Opened 2019-10-07 16:58 UTC by ArtyomAfanasov

2019-10-07 17:02 UTC, ArtyomAfanasov commented
Пояснение коммита с недоумевающим сообщением: "Бетта редукция работает на теореме S K K = I. Но так же и работает нормально и без альфа-конверсии :/"

Работает нормально, т.к. конфликтов не происходит ввиду того, что параметр `x` при первой бета-редукции исчезает из лямбда-абстракции.
Теперь недоумения нет :)

2019-10-07 17:03 UTC, ArtyomAfanasov commented
Тесты ещё нужно порефакторить: удалить лишние, дать полное название. 
Залью в следующих коммитах

2019-10-07 17:13 UTC, yurii-litvinov requested changes

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +    | Applique of Term * Term
Application

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +    | LambdaAbstract of char * Term
LambdaAbstraction

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +/// Выполнить бетта-редукцию.
Она "бета-редукция"

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +            else Variable(nameInLamdaAbstract)
`else term` то же самое, но короче

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +let bettaReduction replacementName termForSubstitution argument =
Бетар редукция --- это применение аппликации к лямбда-абстракции. А эта функция делает то, что называется "подстановка" :)

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +                debug
Если учесть, что функция --- это не редукция, а подстановка, то можно было не разбирать эти случаи --- подстановка просто бежит по структуре терма и заменяет все свободные вхождения подставляемой переменной на терм, всего три случая.

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +        | Applique(func, _) -> count (number + 1) func
Аппликации внутри терма справа Вас не интересуют?

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +            | Variable(name) -> Applique(Variable(name), argument)
Тут вообще вместо `Applique(Variable(name), argument)` можно было написать `term`

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +            | Applique(_, _) -> Applique(findAndReduceRedex func, argument)
Редэксы справа нас не интересуют? Почему?

2019-10-07 17:13 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/Interpreter.fs
> +            | LambdaAbstract(name, nextTerm) -> bettaReduction name nextTerm argument
А если после подстановки ещё остались редэксы?

2019-10-18 20:30 UTC, ArtyomAfanasov commented
В задаче я наделал много коммитов. Могу их объединить для чистоты и красоты пуллреквеста в несколько коммитов. Но я хотел бы оставить их все для истории :)
Т.е. не хочу, чтобы Вы думали, будто бы я не умею работать с гитом относительно чистоты коммитов :)

2019-10-19 12:14 UTC, yurii-litvinov approved these changes
Да, в целом всё правильно, зачтена

2019-10-19 12:14 UTC, yurii-litvinov commented on Interpreter/tests/Interpreter.Tests/Interpreter.Tests.fs
> +    // Can i avoid such terrible DU?
Можно определит предметно-ориентированный язык на операторах, который бы конструировал лямбда-выражения. Например, в таком виде:
```fsharp
    let (!) value = Variable(value)
    let (*) name term = LambdaAbstraction(name, term)
    let (+) term1 term2 = Application(term1, term2)
```
И тогда можно было бы писать
```fsharp
let firstPart = !'1' + !'2'
```

2019-10-19 12:14 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/AttractiveInterpreter.fs
> +                    Variable((char)(name.ToString().ToUpperInvariant()))
А почему Вы думаете, что то, что получится, будет не в conflictNames?

2019-10-19 12:14 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/AttractiveInterpreter.fs
> +                Application(perform func , perform argument )
С пробелами беда

2019-10-19 12:14 UTC, yurii-litvinov commented on Interpreter/src/Interpreter/AttractiveInterpreter.fs
> +            | Application(func, argumenmt) ->
argumenmt, опечатка

2019-10-22 09:21 UTC, ArtyomAfanasov commented on Interpreter/tests/Interpreter.Tests/Interpreter.Tests.fs
> +    // Can i avoid such terrible DU?
Удобно!

2019-11-02 12:57 UTC, merged